### Pandas
It is a powerful data maniplulation libray in python, widly used for for analysis and data cleaning. it has two primary data structures: series and DataFrams. Series - one-dimensional array like objects. DataFrames - two-dimensional, size-mutable, and potentially heterogenous tabular data structure with labled axes(rows and columns)

In [1]:
import pandas as pd

In [5]:
### series
### it is a one dimensional array with index and values
### it can be created from list, dict, numpy array
data = [1,2,3,4,5,6]
series = pd.Series(data)
print(series)

dict = {'a':1, 'b':2, 'c':3}
series = pd.Series(dict)
print(series)

data = [1,2,3,4,5,6]
i = ['a','b','c','d','e','f']   
series = pd.Series(data, index = i )
print(series)

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [53]:
#### dataframe
### it is a 2 dimensional array with index and columns
data = {'name': ['rakshith', 'sachin', 'pranav'], 'age': [20, 21, 22], 'city': ['bangalore', 'mumbai', 'delhi']}
df = pd.DataFrame(data)
print(df)

import numpy as np
np.array(df)

data2= [{'name': 'rakshith', 'age': 20, 'city': 'bangalore'},
       {'name': 'sachin', 'age': 21, 'city': 'mumbai'},
       {'name': 'pranav', 'age': 22, 'city': 'delhi'},
       {'name': 'sachin', 'age': 21, 'city': 'mumbai'},
    ]      
df = pd.DataFrame(data2)
print(df)

       name  age       city
0  rakshith   20  bangalore
1    sachin   21     mumbai
2    pranav   22      delhi
       name  age       city
0  rakshith   20  bangalore
1    sachin   21     mumbai
2    pranav   22      delhi
3    sachin   21     mumbai

In [4]:
dfc = pd.read_csv('sales_data_sample.csv', encoding='cp1252')
dfc.head(5)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium

In [25]:
dfc.tail(5)

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [52]:
df

NameError: name 'df' is not defined

In [54]:
print(df['name'] ,"\n")
print(df.loc[0] ,"\n")

print(df.iloc[0, 0], "\n")
###iloc is used to access the data by index position

0    rakshith
1      sachin
2      pranav
3      sachin
Name: name, dtype: str

name     rakshith
age            20
city    bangalore
Name: 0, dtype: object

rakshith

In [55]:
print(df.at[2, 'name'])###at is used to access the data by label position
print(df.iat[2, 2])###iat is used to access the data by index position

df['salary'] = [50000, 60000, 70000, 80000]
###print(df)

df.drop('salary', axis=1) ### axix= 0-> checks in row,axis=1 is used to drop the column
print(df)#### it will not drop the column permanently
df.drop('salary', axis=1, inplace=True) ### inplace is used to drop the column permanently
print(df)

pranav
delhi
       name  age       city  salary
0  rakshith   20  bangalore   50000
1    sachin   21     mumbai   60000
2    pranav   22      delhi   70000
3    sachin   21     mumbai   80000
       name  age       city
0  rakshith   20  bangalore
1    sachin   21     mumbai
2    pranav   22      delhi
3    sachin   21     mumbai

In [71]:
df['age'] = df['age'] + 1
df

       name  age       city
0  rakshith   21  bangalore
1    sachin   22     mumbai
2    pranav   23      delhi
3    sachin   22     mumbai

In [81]:
df.drop(2, inplace=True)  ### drop the first row permanently by position
print(df)

       name  age       city
0  rakshith   20  bangalore
1    sachin   21     mumbai
3    sachin   21     mumbai

In [85]:
print("Data types:\n", dfc.dtypes)# it will show the data types of each column

dfc.describe()# it will show the statistical summary of the numerical columns

Data types:
 ORDERNUMBER           int64
QUANTITYORDERED       int64
PRICEEACH           float64
ORDERLINENUMBER       int64
SALES               float64
ORDERDATE               str
STATUS                  str
QTR_ID                int64
MONTH_ID              int64
YEAR_ID               int64
PRODUCTLINE             str
MSRP                  int64
PRODUCTCODE             str
CUSTOMERNAME            str
PHONE                   str
ADDRESSLINE1            str
ADDRESSLINE2            str
CITY                    str
STATE                   str
POSTALCODE              str
COUNTRY                 str
TERRITORY               str
CONTACTLASTNAME         str
CONTACTFIRSTNAME        str
DEALSIZE                str
dtype: object

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,QTR_ID,MONTH_ID,YEAR_ID,MSRP
count,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.000000,2823.00000,2823.000000
mean,10258.725115,35.092809,83.658544,6.466171,3553.889072,2.717676,7.092455,2003.81509,100.715551
std,92.085478,9.741443,20.174277,4.225841,1841.865106,1.203878,3.656633,0.69967,40.187912
min,10100.000000,6.000000,26.880000,1.000000,482.130000,1.000000,1.000000,2003.00000,33.000000
25%,10180.000000,27.000000,68.860000,3.000000,2203.430000,2.000000,4.000000,2003.00000,68.000000
50%,10262.000000,35.000000,95.700000,6.000000,3184.800000,3.000000,8.000000,2004.00000,99.000000
75%,10333.500000,43.000000,100.000000,9.000000,4508.000000,4.000000,11.000000,2004.00000,124.000000
max,10425.000000,97.000000,100.000000,18.000000,14082.800000,4.000000,12.000000,2005.00000,214.000000

In [ ]:
dfc['PHONE'] = dfc['PHONE'].astype(str)### it will convert the data type of the column to string

In [5]:
print(dfc.isnull())### it will show the null values in the dataframe
print(dfc.isnull().any())### it will show if there is any null value in the dataframe by column
print(dfc.isnull().any(axis=1))### it will show if there is any null value in the dataframe by row

      ORDERNUMBER  QUANTITYORDERED  PRICEEACH  ORDERLINENUMBER  SALES  \
0           False            False      False            False  False
1           False            False      False            False  False
2           False            False      False            False  False
3           False            False      False            False  False
4           False            False      False            False  False
...           ...              ...        ...              ...    ...
2818        False            False      False            False  False
2819        False            False      False            False  False
2820        False            False      False            False  False
2821        False            False      False            False  False
2822        False            False      False            False  False

      ORDERDATE  STATUS  QTR_ID  MONTH_ID  YEAR_ID  ...  ADDRESSLINE1  \
0         False   False   False     False    False  ...         False
1         False   False   False     False    False  ...         False
2         False   False   False     False    False  ...         False
3         False   False   False     False    False  ...         False
4         False   False   False     False    False  ...         False
...         ...     ...     ...       ...      ...  ...           ...
2818      False   False   False     False    False  ...         False
2819      False   False   False     False    False  ...         False
2820      False   False   False     False    False  ...         False
2821      False   False   False     False    False  ...         False
2822      False   False   False     False    False  ...         False

      ADDRESSLINE2   CITY  STATE  POSTALCODE  COUNTRY  TERRITORY  \
0             True  False  False       False    False       True
1             True  False   True       False    False      False
2             True  False   True       False    False      False
3             True  False  False       False    False       True
4             True  False  False        True    False       True
...            ...    ...    ...         ...      ...        ...
2818          True  False   True       False    False      False
2819          True  False   True       False    False      False
2820          True  False   True       False    False      False
2821          True  False   True       False    False      False
2822          True  False  False       False    False       True

      CONTACTLASTNAME  CONTACTFIRSTNAME  DEALSIZE
0               False             False     False
1               False             False     False
2               False             False     False
3               False             False     False
4               False             False     False
...               ...               ...       ...
2818            False             False     False
2819            False             False     False
2820            False             False     False
2821            False             False     False
2822            False             False     False

[2823 rows x 25 columns]
ORDERNUMBER         False
QUANTITYORDERED     False
PRICEEACH           False
ORDERLINENUMBER     False
SALES               False
ORDERDATE           False
STATUS              False
QTR_ID              False
MONTH_ID            False
YEAR_ID             False
PRODUCTLINE         False
MSRP                False
PRODUCTCODE         False
CUSTOMERNAME        False
PHONE               False
ADDRESSLINE1        False
ADDRESSLINE2         True
CITY                False
STATE                True
POSTALCODE           True
COUNTRY             False
TERRITORY            True
CONTACTLASTNAME     False
CONTACTFIRSTNAME    False
DEALSIZE            False
dtype: bool
0       True
1       True
2       True
3       True
4       True
        ...
2818    True
2819    True
2820    True
2821    True
2822    True
Length: 2823, dtype: bool

In [10]:
print(dfc.isnull().sum())### it will show the count of null values in each column

ORDERNUMBER            0
QUANTITYORDERED        0
PRICEEACH              0
ORDERLINENUMBER        0
SALES                  0
ORDERDATE              0
STATUS                 0
QTR_ID                 0
MONTH_ID               0
YEAR_ID                0
PRODUCTLINE            0
MSRP                   0
PRODUCTCODE            0
CUSTOMERNAME           0
PHONE                  0
ADDRESSLINE1           0
ADDRESSLINE2        2521
CITY                   0
STATE               1486
POSTALCODE            76
COUNTRY                0
TERRITORY           1074
CONTACTLASTNAME        0
CONTACTFIRSTNAME       0
DEALSIZE               0
dtype: int64

In [13]:
dfc.fillna(0)### it will fill the null values with 0 temporarily
dfc.fillna(dfc['SALES'].mean())### it will fill the null values with the mean of the column temporarily
### dfc['SALES'].fillna(dfc['SALES'].mean(), inplace=True)### it will fill the null values with the mean of the column permanently

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,3553.889072,NYC,NY,10022,USA,3553.889072,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,3553.889072,Reims,3553.889072,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,3553.889072,Paris,3553.889072,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,3553.889072,Pasadena,CA,90003,USA,3553.889072,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,3553.889072,San Francisco,CA,3553.889072,USA,3553.889072,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",3553.889072,Madrid,3553.889072,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,3553.889072,Oulu,3553.889072,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",3553.889072,Madrid,3553.889072,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,3553.889072,Toulouse,3553.889072,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,3553.889072,Boston,MA,51003,USA,3553.889072,Yoshido,Juri,Medium

In [19]:
dfc.rename(columns = {'SALES' : 'SALES_AMOUNT'})### it will rename the column te,mporarily
###dfc.columns

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES_AMOUNT,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,NaN,NYC,NY,10022,USA,NaN,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,NaN,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,NaN,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,NaN,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,NaN,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Torikatu 38,NaN,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,"C/ Moralzarzal, 86",NaN,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,1 rue Alsace-Lorraine,NaN,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,8616 Spinnaker Dr.,NaN,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium

In [28]:
dfc['PRICEEACH1'] = dfc['PRICEEACH'].astype(int)### it will convert the data type of the column to integer
dfc.dtypes

ORDERNUMBER           int64
QUANTITYORDERED       int64
PRICEEACH           float64
ORDERLINENUMBER       int64
SALES               float64
ORDERDATE               str
STATUS                  str
QTR_ID                int64
MONTH_ID              int64
YEAR_ID               int64
PRODUCTLINE             str
MSRP                  int64
PRODUCTCODE             str
CUSTOMERNAME            str
PHONE                   str
ADDRESSLINE1            str
ADDRESSLINE2            str
CITY                    str
STATE                   str
POSTALCODE              str
COUNTRY                 str
TERRITORY               str
CONTACTLASTNAME         str
CONTACTFIRSTNAME        str
DEALSIZE                str
PRICEEACH1            int64
dtype: object

In [31]:
dfc['SALES2'] = dfc['SALES']*2 ### it will create a new column by multiplying the existing column with 2
dfc['SALES2'] = dfc['SALES'].apply(lambda x: x*2)### it will apply the function to each element of the column
### same as above but using lambda function
dfc

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE,PRICEEACH1,SALES2
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,NYC,NY,10022,USA,NaN,Yu,Kwai,Small,95,5742.00
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,Reims,NaN,51100,France,EMEA,Henriot,Paul,Small,81,5531.80
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,Paris,NaN,75508,France,EMEA,Da Cunha,Daniel,Medium,94,7768.68
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,Pasadena,CA,90003,USA,NaN,Young,Julie,Medium,83,7493.40
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,San Francisco,CA,NaN,USA,NaN,Brown,Julie,Medium,100,10410.54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,4,12,2004,...,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Small,100,4488.80
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,1,1,2005,...,Oulu,NaN,90110,Finland,EMEA,Koskitalo,Pirkko,Medium,100,7957.02
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,1,3,2005,...,Madrid,NaN,28034,Spain,EMEA,Freyre,Diego,Medium,100,10835.14
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,1,3,2005,...,Toulouse,NaN,31000,France,EMEA,Roulet,Annette,Small,62,4232.32
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,2,5,2005,...,Boston,MA,51003,USA,NaN,Yoshido,Juri,Medium,65,6158.88

In [40]:
group_mean = dfc.groupby('PRODUCTLINE')['SALES'].mean()
group_mean### it will group the data by PRODUCTLINE and calculate the mean of sales for each PRODUCTLINE

group_sum = dfc.groupby(['PRODUCTLINE', 'COUNTRY'])['SALES'].sum()
group_sum### it will group the data by PRODUCTLINE and COUNTRY and calculate the sum of sales for each group

group_agg = dfc.groupby('PRODUCTLINE')['SALES'].agg(['mean', 'sum', 'count']) ### it will group the data by PRODUCTLINE and calculate the mean, sum and count of sales for each PRODUCTLINE
group_agg

                         mean         sum  count
PRODUCTLINE
Classic Cars      4053.377104  3919615.66    967
Motorcycles       3523.831843  1166388.34    331
Planes            3186.286176   975003.57    306
Ships             3053.150128   714437.13    234
Trains            2938.226883   226243.47     77
Trucks and Buses  3746.810100  1127789.84    301
Vintage Cars      3135.339110  1903150.84    607

In [42]:
df1 = pd.DataFrame({'Key': ['A', 'B', 'C'], 'Value1': [1, 2, 3]})
df2 = pd.DataFrame({'Key': ['A', 'B', 'D'], 'Value2': [4, 5, 6]})

In [ ]:
print(pd.merge(df1,df2 ,on='Key' ,how= 'inner'), "\n")### it will merge the two dataframes based on the common column 'Key' and return only the rows that have matching keys in both dataframes
print(pd.merge(df1,df2 ,on='Key' ,how= 'outer'), "\n")### it will  merge the two dataframes based on the common column 'Key' and return all the rows from both dataframes, filling in NaN for missing values
print(pd.merge(df1,df2 ,on='Key' ,how= 'left'), "\n")### it will merge the two dataframes based on the common column 'Key' and return all the rows from the left dataframe, filling in NaN for missing values in the right dataframe
print(pd.merge(df1,df2 ,on='Key' ,how= 'right'), "\n")### it will merge the two dataframes based on the common column 'Key' and return all the rows from the right dataframe, filling in NaN for missing values in the left dataframe
print(pd.merge(df1, df2, how='cross'), "\n")### it will merge the two dataframes based on the common column 'Key' and return all the possible combinations of rows from both dataframes

  Key  Value1  Value2
0   A       1       4
1   B       2       5

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

  Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6

  Key_x  Value1 Key_y  Value2
0     A       1     A       4
1     A       1     B       5
2     A       1     D       6
3     B       2     A       4
4     B       2     B       5
5     B       2     D       6
6     C       3     A       4
7     C       3     B       5
8     C       3     D       6

In [3]:
import pandas as pd
from io import StringIO
Data  = '{"employee_name": "James", "email":"adagaga","job_title":[{"title1": "data scientist" , "title2": "data analyst"}]}'
df = pd.read_json(StringIO(Data))

In [4]:
df

  employee_name    email                                          job_title
0         James  adagaga  {'title1': 'data scientist', 'title2': 'data a...

In [8]:
print(df.to_json())### it will convert the dataframe to json format
print(df.to_json(orient='index'))### it will convert the dataframe to json format with index orientation
print(df.to_json(orient='records'))### it will convert the dataframe to json format with records orientation

{"employee_name":{"0":"James"},"email":{"0":"adagaga"},"job_title":{"0":{"title1":"data scientist","title2":"data analyst"}}}
{"0":{"employee_name":"James","email":"adagaga","job_title":{"title1":"data scientist","title2":"data analyst"}}}
[{"employee_name":"James","email":"adagaga","job_title":{"title1":"data scientist","title2":"data analyst"}}]

In [11]:
df = pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data", header=None)### it will read the csv file from the url and return a dataframe
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [13]:
df.to_csv('wine_data.csv')### it will save the dataframe to a csv file named 'wine_data.csv' in the current working directory

In [15]:
!pip install lxml

Collecting lxml
  Downloading lxml-6.1.0-cp314-cp314-win_amd64.whl.metadata (4.1 kB)
Downloading lxml-6.1.0-cp314-cp314-win_amd64.whl (4.1 MB)
   ---------------------------------------- 0.0/4.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.1 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.1 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.1 MB 1.6 MB/s eta 0:00:03
   ---------- ----------------------------- 1.0/4.1 MB 1.6 MB/s eta 0:00:02
   ------------ --------------------------- 1.3/4.1 MB 1.6 MB/s eta 0:00:02
   ------------------ --------------------- 1.8/4.1 MB 1.7 MB/s eta 0:00:02
   -------------------- ------------------- 2.1/4.1 MB 1.6 MB/s eta 0:00:02
   ----------------------- ---------------- 2.4/4.1 MB 1.7 MB/s eta 0:00:02
   ------------------------- -------------- 2.6/4.1 MB 1.7 MB/s eta 0:00:01
   ------------------------------ --------- 3.1/4.1 MB 1.7 MB/s eta 0:00:01
   --------------------------------- ------ 3.4/4.1 MB 1.7 MB/s eta 0:00:01
   ------------------------------------ --- 3.7/4.1 MB 1.7 MB/s eta 0:00:01
   -------------------------------------- - 3.9/4.1 MB 1.7 MB/s eta 0:00:01
   ---------------------------------------- 4.1/4.1 MB 1.6 MB/s  0:00:02
Installing collected packages: lxml
Successfully installed lxml-6.1.0

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [28]:
url="https://www.fdic.gov/bank-failures/failed-bank-list?combine=&items_per_page=All&antibot_key=oYFeUMWNuogMXp18XjtLxFlxEB5JgvXAHuQUeVJlnGY"
df = pd.read_html(url)
df[0]### it will read the html table from the url and return a list of dataframes, we can access the first dataframe using index 0

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
1,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
2,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
3,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
4,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
...,...,...,...,...,...,...,...
569,Sinclair National Bank,Gravette,Arkansas,34248,Delta Trust & Bank,"September 7, 2001",4649
570,Malta National Bank,Malta,Ohio,6629,North Valley Bank,"May 3, 2001",4648
571,First Alliance Bank & Trust Co.,Manchester,New Hampshire,34264,Southern New Hampshire Bank & Trust,"February 2, 2001",4647
572,The National State Bank of Metropolis,Metropolis,Illinois,3815,Banterra Bank of Marion,"December 14, 2000",4646
573,Bank of Honolulu,Honolulu,Hawaii,21029,Bank of the Orient,"October 13, 2000",4645